### ISSUE TITLE
NullPointerException in com.android.phone

### ISSUE THREAD

**Issue by stiller-leser** [LineageOS/android_device_motorola_nash#5]
Hi all,

first off: Thank you for keeping the device alive! I have been encountering the following issue causing constants reboots. This happens with the LineageOS build 20200404 and the OpenGapps from 20200403. The phone does not yet have a SIM in it.

```
04-05 00:32:29.678  7296  7296 I TelecomFramework: PstnIncomingCallNotifier: Registering: Handler (com.qualcomm.qti.internal.telephony.QtiGsmCdmaPhone) {b1d780f}
04-05 00:32:29.684  7296  7296 E QImsService:  : onSubscriptionsChanged unable to process due to SubscriptionInfo is null
04-05 00:32:29.686  7296  7296 E QImsService: ImsServiceSub : [0] onSubscriptionsChanged unable to process due to SubscriptionInfo is null
04-05 00:32:29.687  7296  7296 E QImsService:  : onSubscriptionsChanged unable to process due to SubscriptionInfo is null
04-05 00:32:29.687  7296  7296 E QImsService: ImsServiceSub : [1] onSubscriptionsChanged unable to process due to SubscriptionInfo is null
04-05 00:32:29.688  7296  7296 D QtiMultiSimSettingController: onSubscriptionsChanged
04-05 00:32:29.688  7296  7296 D QtiMultiSimSettingController: updateDefaults
04-05 00:32:29.688  7296  7296 D QtiMultiSimSettingController: [updateDefaultValues] No active sub. Setting default to INVALID sub.
04-05 00:32:29.691  1975  1975 V KeyguardUpdateMonitor: onSubscriptionInfoChanged()
04-05 00:32:29.696  7296  7296 D QtiMultiSimSettingController: disableDataForNonDefaultNonOpportunisticSubscriptions - do nothing
04-05 00:32:29.698  7296  7296 W PhoneGlobals: Can't get phone with sub id = -1
04-05 00:32:29.699  7296  7296 W PhoneGlobals: Can't get phone with sub id = -1
04-05 00:32:29.699  7296  7296 I QImsService: ImsSubControllerHandler : Message received: what = 2
04-05 00:32:29.699  7296  7296 I QImsService: ImsSubControllerHandler : Received SubConfig Event phoneId = 0
04-05 00:32:29.700  7296  7296 I QImsService: ImsSubController : handleSubConfigException error : 6
04-05 00:32:29.700  7296  7296 I QImsService: ImsSubController : initSubscriptionStatus: [Multi-sim] Using RAF and DDS to decide IMS Sub
04-05 00:32:29.701  7296  7296 E QImsService: ImsSubController : handleRafInfoChange: subIds not valid
04-05 00:32:29.702  7296  7296 E QImsService: ImsSubController : handleRafInfoChange: subIds not valid
04-05 00:32:29.702  7296  7296 I QImsService: ImsSubController : handleRafInfoChange: NumPhones: 2Multiple Multimode stacks: 0
04-05 00:32:29.702  7296  7296 V QImsService: ImsSubController : notifyStackConfigChanged: activeStacks:[true, false, false, false, false, false] phoneId: 0
04-05 00:32:29.702  7296  7296 I QImsService: ImsServiceSub : [0] onStackConfigChanged :: activeStacks[0]=true
04-05 00:32:29.703  7296  7296 I QImsService: ImsServiceSub : [0] oldFeatureState = 0
04-05 00:32:29.703  7296  7296 I ImsFeature: notifying ImsFeatureState=2
04-05 00:32:29.703  7296  7296 I ImsServiceController: notifyImsFeatureStatus: slot=0, feature=1, status=2
04-05 00:32:29.704  7296  7296 I QImsService: ImsServiceSub : [1] onStackConfigChanged :: activeStacks[1]=false
04-05 00:32:29.704  7296  7296 I QImsService: ImsServiceSub : [1] oldFeatureState = 0
04-05 00:32:29.704  7296  7296 I QImsService: ImsSubController : switchImsPhone: ImsPhoneId: -1 changed to 0
04-05 00:32:29.705  7296  7296 D AndroidRuntime: Shutting down VM
04-05 00:32:29.706  7296  7296 E AndroidRuntime: FATAL EXCEPTION: main
04-05 00:32:29.706  7296  7296 E AndroidRuntime: Process: com.android.phone, PID: 7296
04-05 00:32:29.706  7296  7296 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from null array
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at org.codeaurora.ims.ImsSubController.isCarrierConfigLoaded(ImsSubController.java:693)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at org.codeaurora.ims.ImsSubController.updateActiveImsStackForPhoneId(ImsSubController.java:464)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at org.codeaurora.ims.ImsSubController.handleRafInfoChange(ImsSubController.java:573)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at org.codeaurora.ims.ImsSubController.initSubscriptionStatus(ImsSubController.java:414)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at org.codeaurora.ims.ImsSubController.handleSubConfigException(ImsSubController.java:249)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at org.codeaurora.ims.ImsSubController.handleSubConfigChanged(ImsSubController.java:257)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at org.codeaurora.ims.ImsSubController.access$000(ImsSubController.java:43)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at org.codeaurora.ims.ImsSubController$ImsSubControllerHandler.handleMessage(ImsSubController.java:301)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-05 00:32:29.706  7296  7296 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
04-05 00:32:29.710  1362  5680 W RescueParty: Noticed 5 events for UID 1001 in last 8 sec
04-05 00:32:29.711  1362  5680 W PackageManager: Incremented rescue level to FACTORY_RESET triggered by UID 1001
04-05 00:32:29.712  1362  7385 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
04-05 00:32:29.713  1362  5680 W RescueParty: Attempting rescue level FACTORY_RESET
04-05 00:32:30.371  1362  1381 E LightsService: Light requested not available on this device. 2
04-05 00:32:30.702  6630  7390 I FirebaseCrash: Sending crashes
04-05 00:32:30.741  7386  7386 I /system/bin/uncrypt:   received command: [--prompt_and_wipe_data
04-05 00:32:30.741  7386  7386 I /system/bin/uncrypt: --reason=RescueParty
04-05 00:32:30.741  7386  7386 I /system/bin/uncrypt: --locale=de_DE
04-05 00:32:30.741  7386  7386 I /system/bin/uncrypt: ] (59)
04-05 00:32:30.750  7386  7386 I /system/bin/uncrypt:   received 0, exiting now
04-05 00:32:30.750  1362  5680 I RecoverySystemService: uncrypt setup bcb successfully finished.
04-05 00:32:30.753  1362  1492 D ShutdownThread: Notifying thread to start shutdown longPressBehavior=1
04-05 00:32:30.757  1362  1492 E system_server: Invalid ID 0x00000000.
04-05 00:32:30.798  1362  7392 I ShutdownThread: Sending shutdown broadcast...
04-05 00:32:30.803   929   956 E PerMgrSrv: cnss-daemon registered for modem has died
04-05 00:32:30.803   929   956 D PerMgrSrv: modem num voters is 5
04-05 00:32:30.803   929   956 D PerMgrSrv: modem state: is on-line, remove client cnss-daemon
04-05 00:32:30.810   929   956 E PerMgrSrv: PM-PROXY-THREAD registered for modem has died
04-05 00:32:30.810   929   956 D PerMgrSrv: modem num voters is 4
04-05 00:32:30.810   929   956 D PerMgrSrv: modem state: is on-line, remove client PM-PROXY-THREAD
04-05 00:32:30.820  1362  7391 I AdrenoGLES: QUALCOMM build                   : f2ab992, I401605978b
04-05 00:32:30.820  1362  7391 I AdrenoGLES: Build Date                       : 09/28/19
04-05 00:32:30.820  1362  7391 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.01
04-05 00:32:30.820  1362  7391 I AdrenoGLES: Local Branch                     : 
04-05 00:32:30.820  1362  7391 I AdrenoGLES: Remote Branch                    : 
04-05 00:32:30.820  1362  7391 I AdrenoGLES: Remote Branch                    : 
04-05 00:32:30.820  1362  7391 I AdrenoGLES: Reconstruct Branch               : 
04-05 00:32:30.820  1362  7391 I AdrenoGLES: Build Config                     : S L 8.0.11 AArch64
04-05 00:32:30.827  1362  7391 I AdrenoGLES: PFP: 0x005ff112, ME: 0x005ff066
04-05 00:32:30.966  1362  1492 W Looper  : Slow dispatch took 158ms android.ui h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver@6c8ce6 m=0
```

Let me know if I can provide any additional information and stay safe!

All the best,
stiller-leser

**Comment by ThEMarD** [comment]
https://wiki.lineageos.org/bugreport-howto.html
